### ISSUE TITLE
Wrong derivative for the squared error

### ISSUE THREAD

**Issue by lfaucon** [ADGEfficiency/teaching-monolith#1]
Dear @ADGEfficiency 
Thank you for sharing your teaching materials which I found from your reddit post.

I believe this derivative in the file [intro-to-backprop](https://github.com/ADGEfficiency/teaching-monolith/blob/master/backprop/intro-to-backprop.ipynb) is wrong:

![Screen Shot 2019-07-18 at 14 31 22](https://user-images.githubusercontent.com/8818081/61457621-014d1580-a969-11e9-930d-fe6b973781dd.png)

The correct derivative should be:

![CodeCogsEqn](https://user-images.githubusercontent.com/8818081/61458432-c51ab480-a96a-11e9-947d-d1c707929577.gif)

**Comment by ADGEfficiency** [comment]
You are totally correct - this actually came up in class!  I'm working on a fix - also going to add this to the Calc 101 section.

**Comment by ADGEfficiency** [comment]
This is fixed in e0a88b5
